config/routes.rb
class Subdomain
  def self.matches?(request)
    case request.subdomain
      when 'www', '', nil
        false
      else
        true
    end
  end
end

require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users, :controllers => {registrations: 'registrations',
                                      sessions: 'sessions',
                                      invitations: 'invitations'}

  constraints(Subdomain) do
    match '/' => 'home#index', via: :get
  end
  resources :home, only: [:index, :show] do
    get 'edit', on: :collection
  end
  resources :incomes
  resources :expenses
  resources :income_categories
  resources :expense_categories
  resources :roles
  resources :companies
  resources :transactions, only: [:index]
  namespace :api do
    namespace :v1 do
      post 'auth_user' => 'authentications#authenticate_user'
      resources :users
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'

  root 'welcome#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user

  def index
    @invited_for_company = User.where(company_id: @user.company_id)
  end

  def show
  @user = User.find_by(id: params[:id])
  end


  def create


  end


  def edit

  end


  def update

  end

  def destroy

  end


  def set_user
    @user = current_user
  end

end

app/views/home/edit.html.erb
<div class="container">
  <h1>Edit Profile</h1>
</div>

app/views/home/index.html.erb
<h1 align="center">Profile</h1>
<div class="beautiful_line"></div>
<div class="row">

  <div class="col-xs-9">
    <h3>Personal</h3>
    <hr class="hr">
    <table>
      <tr>
        <td class="col-xs-1"><b>Name: </b></td>
        <td><%= current_user.name %></td>
      </tr>
      <tr>
        <td class="col-xs-1"><b>Email: </b></td>
        <td><%= current_user.email %></td>
      </tr>
    </table>
    <br>
    <h3>Company</h3>
    <hr class="hr">
    <table>
      <tr>
        <td class="col-xs-3"><b>Company Name: </b></td>
        <td><%= current_user.company.name %></td>
      </tr>
      <tr>
        <td class="col-xs-1"><b>Subdomain: </b></td>
        <td><%= current_user.company.subdomain %></td>
      </tr>
      <tr>
        <td class="col-xs-1"><b>Phone Numbers: </b></td>
        <td> <% current_user.company.phone_numbers.each do |num| %>
            <%= num.number %> &nbsp;
        <% end %> </td>
      </tr>
    </table>
    <br>
    <p class="center"><%= link_to 'Edit', edit_company_path(id: current_user.id) , class: 'btn     btn-primary big-button' %></p>

    <hr>

    <h3>Invitations</h3>

    <table class="table col-xs-12">
      <tr>
        <th class="col-xs-2">Name</th>
        <th class="col-xs-2">Email</th>
        <th class="col-xs-2">Status</th>
        <th class="col-xs-2">Role</th>
        <th class="col-xs-1"></th>
      </tr>
      <% if policy(:user).index? %>
          <% @invited_for_company.each do |invited| %>
              <tr>
                <td><%= invited.name %></td>
                <td><%= invited.email %></td>
                <td><%= invited.invited_by_id.nil? ? 'Admin':(invited.invitation_accepted_at.present? ? 'Accepted':'Pending') %></td>
                <td><%= invited.role.title%></td>
                <td>
                  <%= link_to 'View', home_path(id: invited.id), class: 'btn btn-sm btn-primary' %>
                </td>
              </tr>
          <% end %>

      <% else %>
          <td colspan="5"><i>You are not allowed to view this ...</i></td>
      <% end %>
    </table>


    <% if policy(:user).new? %>
        <p align="right"><%= link_to 'Invite User', new_user_invitation_path, class: 'btn btn-success' %></p>
    <% end %>
    <br>
  </div>

  <div class="col-xs-3">
    <h3>Profile Picture</h3>
    <hr class="hr">
    <%= image_tag current_user.avatar.url(:thumb) %>

  </div>
</div>

app/views/home/show.html.erb
<h1 class="center">User Details</h1>
<div class="beautiful_line"></div>

<div class="row">
  <div class="col-xs-6">
    <h4><b>Name: </b><%= @user.name%></h4>
    <h4><b>Email: </b><%= @user.email%></h4>
    <h4><b>Permission: </b><%= @user.role.title %></h4><br>

  </div>
  <div class="col-xs-6">
    <%= image_tag @user.avatar.url(:thumb) %>
  </div>

</div>


<div class="card card-block">
  <div class="col-md-4">
    <h3></h3>
  </div>
  <table class="table">
    <thead>
    <tr>
      <th class="col-xs-4">Permission</th>
      <th class="col-xs-2 ">VIEW</th>
      <th class="col-xs-2">CREATE</th>
      <th class="col-xs-2">EDIT</th>
      <th class="col-xs-2">DELETE</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <!-- Income-->
      <td>Income</td>
      <td><%= @user.role.can_view_income ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_create_income ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_edit_income ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_delete_income ? (fa_icon 'check') : (fa_icon 'times') %></td>
    </tr>
    <tr>
      <!-- Income Category-->

      <td>Income Category</td>
      <td><%= @user.role.can_view_income_category ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_create_income_category ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_edit_income_category ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_delete_income_category ? (fa_icon 'check') : (fa_icon 'times') %></td>
    </tr>

    <tr>
      <!-- Expense-->
      <td>Expense</td>
      <td><%= @user.role.can_view_expense ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_create_expense ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_edit_expense ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_delete_expense ? (fa_icon 'check') : (fa_icon 'times') %></td>
    </tr>
    <tr>
      <!-- Expense Category-->
      <td>Expense Category</td>
      <td><%= @user.role.can_view_expense_category ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_create_expense_category ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_edit_expense_category ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_delete_expense_category ? (fa_icon 'check') : (fa_icon 'times') %></td>
    </tr>
    <tr>
      <!-- User-->
      <td>User</td>
      <td><%= @user.role.can_view_user ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_invite_user ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_edit_user ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_delete_user ? (fa_icon 'check') : (fa_icon 'times') %></td>
    </tr>
    <tr>
      <!-- Role-->
      <td>Role</td>
      <td><%= @user.role.can_view_role ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_create_role ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_edit_role ? (fa_icon 'check') : (fa_icon 'times') %></td>
      <td><%= @user.role.can_delete_role ? (fa_icon 'check') : (fa_icon 'times') %></td>
    </tr>
    </tbody>
  </table>
  <br>
  <%= link_to 'Back', home_index_path, class: 'btn btn-sm btn-primary' %>
</div><br>