config/routes.rb
class Subdomain
  def self.matches?(request)
    case request.subdomain
      when 'www', '', nil
        false
      else
        true
    end
  end
end

require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users, :controllers => {registrations: 'registrations',
                                      sessions: 'sessions',
                                      invitations: 'invitations'}

  constraints(Subdomain) do
    match '/' => 'home#index', via: :get
  end
  resources :home, only: [:index, :show] do
    get 'edit', on: :collection
  end
  resources :incomes
  resources :expenses
  resources :income_categories
  resources :expense_categories
  resources :roles
  resources :companies
  resources :transactions, only: [:index]
  namespace :api do
    namespace :v1 do
      post 'auth_user' => 'authentications#authenticate_user'
      resources :users
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'

  root 'welcome#index'

end

app/models/income.rb
class Income < ActiveRecord::Base
  include Filterable

  EXPORT_TYPE = %w(Pdf Excel)

  belongs_to :income_category
  belongs_to :creater, class_name: 'User', foreign_key: :created_by
  belongs_to :updater, class_name: 'User', foreign_key: :updated_by
  has_one :feed, as: :transactionable, class_name: 'Transaction', dependent: :destroy
  mount_uploader :attachment, AttachmentUploader

  validates_numericality_of :amount, presence: true
  validates_presence_of :date
  validates_presence_of :income_category_id

  after_create :create_transaction

  scope :for_start_date, ->(start_date) { where('date >= ?', Date.parse(start_date)) }
  scope :for_end_date, ->(end_date) { where('date <= ?', Date.parse(end_date)) }
  scope :for_user_id, ->(user) { where(created_by: user) }
  scope :for_category_id, ->(category_id) { where(income_category_id: category_id) }

  private
  def create_transaction
    CreateFeedJob.new(self.id).enqueue(wait: 5.seconds)
  end

end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category

  def index
    authorize Income
    @users = company.users

    params[:start_date] = Date.today.beginning_of_month.strftime('%d-%m-%Y') unless params[:start_date].present?
    params[:end_date] = Date.today.end_of_month.strftime('%d-%m-%Y') unless params[:end_date].present?

    @incomes = company.incomes.filter(filter_params(params)).paginate(page: params[:page])
    @income_category_count = @income_categories.joins(:incomes).filter(filter_params(params)).group(:name).count

    respond_to do |format|
      format.html
      format.js
      format.pdf
      format.xls
    end
  end

  def new
    authorize Income
    @income = Income.new
  end

  def create
    authorize Income
    @income = Income.new(income_params)
    @income.save
    set_category_count
  end

  def edit
    authorize Income
    @income_categories = company.income_categories
    @income = Income.find_by(id: params[:id])
  end

  def update
    authorize Income
    @income = Income.find_by(id: params[:id])
    @income.update_attributes(income_params)
    @income.update_columns(updated_by: current_user.id)
    set_category_count
  end

  def destroy
    authorize Income
    @income = Income.find_by(id: params[:id])
    @income.destroy
    set_category_count
  end


  private
  def income_params
    params.require(:income).permit(:date, :amount, :description, :income_category_id, :created_by, :updated_by, :company_id, :attachment)
  end

  def filter_params(params)
    params.slice(:user_id, :start_date, :end_date, :category_id)
  end

  def set_category
    @income_categories = company.income_categories
  end

  def set_category_count
    @income_category_count = @income_categories.joins(:incomes).group(:name).count
  end

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to root_path
  end

end

app/views/incomes/_error.html.erb
<% if @income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
        <% @income.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/incomes/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="exampleModalLabel">New Income</h4>
    </div>
    <%= form_for @income, remote: true do |f| %>
        <div class="modal-body">
          <div id="income_errors"></div>
          <div class="form-group">
            <%= f.label :amount, class: 'control-label '%>
            <%= f.text_field :amount, autofocus: true, class:'form-control'%>
            <%= f.hidden_field :company_id, value: current_user.company.id %>
            <%= f.hidden_field :created_by, value: current_user.id %>
            <%= f.hidden_field :updated_by, value: current_user.id %>
          </div>

          <div class="form-group">
            <%= f.label :description, class: 'control-label ' %>
            <%= f.text_field :description ,class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :category, class: 'control-label ' %>
            <%= collection_select(:income, :income_category_id, @income_categories, :id, :name,
                                  {prompt: 'Select Category'},{class: 'form-control form-group'}) %>
          </div>

          <div class="form-group">
            <%= f.label :date, class: 'control-label ' %>   <br>
            <input type="text" name="income[date]" class="date-input" value="<%=Date.today.strftime('%d-%m-%Y')%>"/>&nbsp;
          </div>

            <div class="form-group">
              <%= f.label :attachment, class: 'control-label ' %>
              <%= f.file_field :attachment %>
            </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit 'Submit', class: 'btn btn-success' %>
        </div>
    <% end %>
  </div>
</div>

app/views/incomes/_income.html.erb
<tr data-id="<%= income.id %>">
  <td><%= income.amount %></td>
  <td><%= income.date.strftime('%d %b, %Y')  %></td>
  <td><%= income.income_category.name %></td>
  <td><%= income.creater.name %></td>
  <td><%= income.updater.name %></td>
  <td><%= link_to_if !income.attachment.blank?, 'Download', income.attachment.url, target: '_blank' %></td>
  <td>
    <% if policy(:income).edit? %>
        <%= link_to 'Edit', edit_income_path(id: income.id), class: 'btn btn-sm btn-primary', remote: true %>
    <% end %>
    <% if policy(:income).destroy? %>
        <%= link_to 'Delete', income_path(id: income.id), class: 'btn btn-sm btn-danger', method:  :delete, remote: true %>
    <% end %>
  </td>
</tr>

app/views/incomes/create.js.erb
<% if @income.errors.any? %>
  $("#income_errors").addClass('alert alert-danger').html("<%= escape_javascript(render 'error') %>").show();
<% else %>
  $("#incomes tbody").prepend("<%= escape_javascript(render partial: 'income', locals: { income: @income }) %>");
  $("#chart").html("<%=escape_javascript(pie_chart @income_category_count) %>");
  $("#myModal").modal('hide');
<% end %>

app/views/incomes/destroy.js.erb
$("tr[data-id='<%=@income.id%>']").remove();
$("#chart").html("<%=escape_javascript(pie_chart @income_category_count) %>");

app/views/incomes/edit.js.erb
$('#myModal').addClass("modal").html("<%= escape_javascript(render 'form') %>").modal({show: true, backdrop: 'static'});
$('.date-input').datepicker({
    format: 'dd-mm-yyyy',
    autoclose: true
});

app/views/incomes/index.html.erb
<h1 class="center">Incomes</h1>
<div class="beautiful_line"></div>


<div class="center">
  <%= form_tag incomes_path, method: 'get', remote: true do %>
      <b>Start Date: </b><input type="text" name="start_date" class="date-input" value="<%=params[:start_date]%>"/>&nbsp;

      <b>End Date: </b><input type="text" name="end_date" class="date-input" value="<%=params[:end_date]%>"/>&nbsp;

      <%= label_tag :user, 'User: ' %>
      <%= collection_select('', :user_id, @users , :id, :name, {selected: params[:user_id], include_blank: 'All'},{ class: 'btn btn-sm btn-default '})%>&nbsp;

      <%= label_tag :category, 'Category: ' %>
      <%= collection_select('', :category_id, @income_categories, :id, :name, {selected: params[:category_id], include_blank: 'All'},{ class: 'btn btn-sm btn-default '})%>&nbsp;

      <%= submit_tag('Go', class: 'btn btn-sm btn-primary') %>


      <div class="dropdown">
        <button class="dropbtn">Export</button>
        <div class="dropdown-content">
          <a href="<%=incomes_path(start_date: params[:start_date],end_date: params[:end_date], user_id: params[:user_id], category_id: params[:category_id], format: :pdf)%>">Pdf</a>
          <a href="<%=incomes_path(start_date: params[:start_date],end_date: params[:end_date], user_id: params[:user_id], category_id: params[:category_id],format: :xls)%>">Xls</a>
        </div>
      </div>


  <% end %>
</div>

<br>


<% if policy(:income).new? %>
    <div class="center">
      <%= link_to 'New Income', new_income_path , class: 'center btn btn-lg btn-success', remote: true  %>
    </div>
    <br>
<% end %>


<table id="incomes" class="table">
  <thead>
  <tr>
    <th class="col-xs-1">Amount</th>
    <th class="col-xs-1">Date</th>
    <th class="col-xs-1">Category</th>
    <th class="col-xs-1">Created By</th>
    <th class="col-xs-1">Updated By</th>
    <th class="col-xs-1">Attachment</th>
    <th class="col-xs-1"></th>
  </tr>
  </thead>
  <tbody>
    <%= render partial: 'income', collection: @incomes %>
  </tbody>
</table>
<hr class="hr">

<h2 class="center">Analytics</h2>
<div class="beautiful_line"></div>
<div id="chart" >
<%= pie_chart @income_category_count %>
</div>

app/views/incomes/index.js.erb
$("#chart").html("<%=escape_javascript(pie_chart @income_category_count) %>");
$("#incomes tbody").html("<%= escape_javascript(render partial: 'income', collection:  @incomes ) %>");

app/views/incomes/index.xls.erb
<h1>Incomes</h1>
<br>

<table>
  <tr>
    <th class="col-xs-1">Amount</th>
    <th class="col-xs-1">Date</th>
    <th class="col-xs-2">Category</th>
    <th class="col-xs-1">Created By</th>
    <th class="col-xs-1">Updated By</th>
    <th class="col-xs-1">Attachment</th>
  </tr>
  <% @incomes.each do |income| %>
      <tr>
        <td><%= income.amount%></td>
        <td><%= income.date.strftime('%d %b, %Y')%></td>
        <td><%= income.income_category.name%></td>
        <td><%= income.creater.name %></td>
        <td><%= income.updater.name %></td>
        <td><%= link_to_if !income.attachment.blank?, 'Download', income.attachment.url, target: '_blank' %></td>
      </tr>
  <% end %>
</table>

app/views/incomes/new.js.erb
$('#myModal').addClass("modal").html("<%= escape_javascript(render 'form') %>").fadeIn(400).modal({show: true, backdrop: 'static'});
$('.date-input').datepicker({
    format: 'dd-mm-yyyy',
    autoclose: true
});

app/views/incomes/update.js.erb
<% if @income.errors.any? %>
    $("#income_errors").html("<%= escape_javascript(render 'error') %>").show();
<% else %>
    $("tr[data-id='<%=@income.id%>']").replaceWith("<%= escape_javascript(render partial: 'income', locals: { income: @income }) %>");
    $("#chart").html("<%=escape_javascript(pie_chart @income_category_count) %>");
    $("#myModal").modal('hide');
<% end %>