config/routes.rb
class Subdomain
  def self.matches?(request)
    case request.subdomain
      when 'www', '', nil
        false
      else
        true
    end
  end
end

require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users, :controllers => {registrations: 'registrations',
                                      sessions: 'sessions',
                                      invitations: 'invitations'}

  constraints(Subdomain) do
    match '/' => 'home#index', via: :get
  end
  resources :home, only: [:index, :show] do
    get 'edit', on: :collection
  end
  resources :incomes
  resources :expenses
  resources :income_categories
  resources :expense_categories
  resources :roles
  resources :companies
  resources :transactions, only: [:index]
  namespace :api do
    namespace :v1 do
      post 'auth_user' => 'authentications#authenticate_user'
      resources :users
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'

  root 'welcome#index'

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category

  def index
    authorize Expense
    @users = company.users

    params[:start_date] = Date.today.beginning_of_month.strftime('%d-%m-%Y') unless params[:start_date].present?
    params[:end_date] = Date.today.end_of_month.strftime('%d-%m-%Y') unless params[:end_date].present?

    @expenses = company.expenses.filter(filter_params(params))
    @expense_category_count = @expense_categories.joins(:expenses).filter(filter_params(params)).group(:name).count

    respond_to do |format|
      format.html
      format.js
      format.pdf
      format.xls
    end
  end

  def new
    authorize Expense
    @expense = Expense.new
  end

  def create
    authorize Expense
    @expense = Expense.new(expense_params)
    @expense.save
    set_category_count
  end

  def edit
    authorize Expense
    @expense = Expense.find_by(id: params[:id])
  end

  def update
    authorize Expense
    @expense = Expense.find_by(id: params[:id])
    @expense.update_attributes(expense_params)
    @expense.update_columns(updated_by: current_user.id)
    set_category_count
  end

  def destroy
    authorize Expense
    @expense = Expense.find_by(id: params[:id])
    @expense.destroy
    set_category_count
  end


  private
  def expense_params
    params.require(:expense).permit(:date, :amount, :description, :expense_category_id, :created_by, :updated_by , :company_id, :attachment)
  end

  def filter_params(params)
    params.slice(:user_id, :start_date, :end_date, :category_id)
  end

  def set_category
    @expense_categories = company.expense_categories
  end

  def set_category_count
    @expense_category_count = @expense_categories.joins(:expenses).group(:name).count
  end

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    redirect_to root_path
  end

end

app/views/expenses/_error.html.erb
<% if @expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
        <% @expense.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/expenses/_expense.html.erb
<tr data-id="<%= expense.id %>">
  <td><%= expense.amount%></td>
  <td><%= expense.date.strftime('%d %b, %Y')%></td>
  <td><%= expense.expense_category.name %></td>
  <td><%= expense.creater.name %></td>
  <td><%= expense.updater.name %></td>
  <td><%= link_to_if !expense.attachment.blank?, 'Download', expense.attachment.url, target: '_blank' %></td>
  <td>
    <% if policy(:expense).edit? %>
        <%= link_to 'Edit', edit_expense_path(id: expense.id), class: 'btn btn-sm btn-primary', remote: true %>
    <% end %>
    <% if policy(:expense).destroy? %>
        <%= link_to 'Delete', expense_path(id: expense.id), class: 'btn btn-sm btn-danger', method:  :delete, remote: true %>
    <% end %>
  </td>
</tr>

app/views/expenses/_form.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">

    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="exampleModalLabel">New Expense</h4>
    </div>

    <%= form_for @expense, remote: true do |f| %>
        <div class="modal-body">
          <div id="expense_errors"></div>
          <div class="form-group">
            <%= f.label :amount, class: 'control-label '%>
            <%= f.text_field :amount, autofocus: true, class:'form-control'%>
            <%= f.hidden_field :company_id, value: current_user.company.id %>
            <%= f.hidden_field :created_by, value: current_user.id %>
            <%= f.hidden_field :updated_by, value: current_user.id %>
          </div>
          <div class="form-group">
            <%= f.label :description, class: 'control-label ' %>
            <%= f.text_field :description ,class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :category, class: 'control-label ' %>
            <%= collection_select(:expense, :expense_category_id, @expense_categories, :id, :name,
                                  {prompt: 'Select Category'},{class: 'form-control form-group'}) %>
          </div>
          <div class="form-group">
            <%= f.label :date, class: 'control-label ' %>   <br>
            <input type="text" name="expense[date]" class="date-input" value="<%=Date.today.strftime('%d-%m-%Y')%>"/>&nbsp;
          </div>
          <div class="form-group">
            <%= f.label :attachment, class: 'control-label ' %>
            <%= f.file_field :attachment %>
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit 'Submit', class: 'btn btn-success' %>
        </div>
    <% end %>

  </div>
</div>

app/views/expenses/create.js.erb
<% if @expense.errors.any? %>
    $("#expense_errors").addClass('alert alert-danger').html("<%= escape_javascript(render 'error') %>").show();
<% else %>
    $("#expenses tbody").prepend("<%= escape_javascript(render partial: 'expense', locals: { expense: @expense }) %>");
    $("#chart").html("<%=escape_javascript(pie_chart @expense_category_count) %>");
    $("#myModal").modal('hide');
<% end %>

app/views/expenses/destroy.js.erb
$("tr[data-id='<%=@expense.id%>']").remove();
$("#chart").html("<%=escape_javascript(pie_chart @expense_category_count) %>");

app/views/expenses/edit.js.erb
$("#myModal").addClass("modal").html("<%= escape_javascript(render 'form') %>").fadeIn(400).modal({show: true, backdrop: 'static'});
$('.date-input').datepicker({
    format: 'dd-mm-yyyy',
    autoclose: true
});

app/views/expenses/index.html.erb
<h1 class="center">Expenses</h1>
<div class="beautiful_line"></div>

<div class="center">
  <%= form_tag expenses_path, method: 'get', remote: true  do %>
      <b>Start Date: </b><input type="text" name="start_date" class="date-input" value="<%=params[:start_date]%>"/>&nbsp;

      <b>End Date: </b><input type="text" name="end_date" class="date-input" value="<%=params[:end_date]%>"/>&nbsp;

      <%= label_tag :user, 'User: ' %>
      <%= collection_select('', :user_id, @users , :id, :name, {selected: params[:user_id], include_blank: 'All'},{ class: 'btn btn-sm btn-default '})%>&nbsp;

      <%= label_tag :category, 'Category: ' %>
      <%= collection_select('', :category_id, @expense_categories, :id, :name, {selected: params[:category_id], include_blank: 'All'},{ class: 'btn btn-sm btn-default '})%>&nbsp;

      <%= submit_tag('Go', class: 'btn btn-sm btn-primary') %>

      <div class="dropdown">
        <button class="dropbtn">Export</button>
        <div class="dropdown-content">
          <a href="<%=expenses_path(start_date: params[:start_date],end_date: params[:end_date], user_id: params[:user_id], category_id: params[:category_id], format: :pdf)%>">Pdf</a>
          <a href="<%=expenses_path(start_date: params[:start_date],end_date: params[:end_date], user_id: params[:user_id], category_id: params[:category_id],format: :xls)%>">Xls</a>
        </div>
      </div>

  <% end %>
</div>

<br>
<% if policy(:expense).new? %>
    <div class="center">
      <%= link_to 'New Expense', new_expense_path , class: 'btn btn-lg btn-success', remote: true  %>
    </div>
    <br>
<% end %>


<table id="expenses" class="table">
  <thead>
  <tr>
    <th class="col-xs-1">Amount</th>
    <th class="col-xs-1">Date</th>
    <th class="col-xs-1">Category</th>
    <th class="col-xs-1">Created By</th>
    <th class="col-xs-1">Updated By</th>
    <th class="col-xs-1">Attachment</th>
    <th class="col-xs-1"></th>
  </tr>
  </thead>
  <tbody>
  <%= render partial: 'expense', collection: @expenses %>
  </tbody>
</table>
<hr class="hr">
<br>
<h2 class="center">Analytics</h2>
<div class="beautiful_line"></div>
<div id="chart">
  <%= pie_chart @expense_category_count %>
</div>

app/views/expenses/index.js.erb
$("#chart").html("<%=escape_javascript(pie_chart @expense_category_count) %>");
$("#expenses tbody").html("<%= escape_javascript(render partial: 'expense', collection:  @expenses ) %>");

app/views/expenses/index.xls.erb
<h1>Expenses</h1>
<br>

<table>
  <tr>
    <th class="col-xs-1">Amount</th>
    <th class="col-xs-1">Date</th>
    <th class="col-xs-2">Category</th>
    <th class="col-xs-1">Created By</th>
    <th class="col-xs-1">Updated By</th>
    <th class="col-xs-1">Attachment</th>
  </tr>
  <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.amount%></td>
        <td><%= expense.date.strftime('%d %b, %Y')%></td>
        <td><%= expense.expense_category.name%></td>
        <td><%= expense.creater.name %></td>
        <td><%= expense.updater.name %></td>
        <td><%= link_to_if !expense.attachment.blank?, 'Download', expense.attachment.url, target: '_blank' %></td>
      </tr>
  <% end %>
</table>

app/views/expenses/new.js.erb
$("#myModal").addClass("modal").html("<%= escape_javascript(render 'form') %>").fadeIn(400).modal({show: true, backdrop: 'static'});
$('.date-input').datepicker({
    format: 'dd-mm-yyyy',
    autoclose: true
});

app/views/expenses/update.js.erb
<% if @expense.errors.any? %>
    $("#expense_errors").addClass('alert alert-danger').html("<%= escape_javascript(render 'error') %>").show();
<% else %>
    $("tr[data-id=<%=@expense.id%>]").replaceWith("<%= escape_javascript(render partial: 'expense', locals: { expense: @expense }) %>");
    $("#chart").html("<%=escape_javascript(pie_chart @expense_category_count) %>");
    $("#myModal").modal('hide');
<% end %>