config/routes.rb
class Subdomain
  def self.matches?(request)
    case request.subdomain
      when 'www', '', nil
        false
      else
        true
    end
  end
end

require 'sidekiq/web'

Rails.application.routes.draw do

  devise_for :users, :controllers => {registrations: 'registrations',
                                      sessions: 'sessions',
                                      invitations: 'invitations'}

  constraints(Subdomain) do
    match '/' => 'home#index', via: :get
  end
  resources :home, only: [:index, :show] do
    get 'edit', on: :collection
  end
  resources :incomes
  resources :expenses
  resources :income_categories
  resources :expense_categories
  resources :roles
  resources :companies
  resources :transactions, only: [:index]
  namespace :api do
    namespace :v1 do
      post 'auth_user' => 'authentications#authenticate_user'
      resources :users
    end
  end

  mount Sidekiq::Web, at: '/sidekiq'

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finance</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>

  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="col-xs-9 container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Finance</a>
    </div>
    <ul class="nav navbar-nav">

      <li><a href="<%= home_index_path %>">Home</a></li>
      <% if policy(:income).index? %>
          <li><a href="<%=incomes_path%>">Incomes</a></li>
      <% end %>

      <li><a href="<%=expenses_path%>">Expenses</a></li>

      <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Manage Categories<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <% if policy(:income_category).index? %>
              <li><a href="<%=income_categories_path%>">Income Category</a></li>
          <% end %>

          <% if policy(:expense_category).index? %>
              <li><a href="<%=expense_categories_path%>">Expense Category</a></li>
          <% end %>

        </ul>
      </li>

      <li><a href="<%=transactions_path%>">Transactions</a></li>
      <li><a href="<%= roles_path %>">Roles</a></li>
    </ul>

  </div>
  <div class="col-xs-3">
    <ul class="nav navbar-nav pull-right">
      <% if current_user %>
          <li><a href="<%= edit_user_registration_path %>">Hi, <%= current_user.email %></a></li>
          <li><a href="<%= destroy_user_session_path %>" data-method="delete">Sign Out</a></li>
      <% else %>

          <li><a href="<%= new_user_session_path %>">Sign In</a></li>
      <% end %>
    </ul>

  </div>

</nav>
<br>
<div class="w3-card-2 w3-white container">
  <div id="flash">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
  <%= yield %>
</div>

<div id="myModal"></div>

</body>
</html>